9.0 mgmtsystem severity
OCA/management-system pull request #157
Opened 2016-09-23 15:24 UTC by naousse

2016-09-26 14:54 UTC, max3903 commented on mgmtsystem_severity/README.rst
> + * Start odoo with the project in the addons path
@naousse 
* No need for installation instructions.

2016-09-26 14:55 UTC, max3903 commented on mgmtsystem_severity/README.rst
> +
* Please add the `Try me on Runbot` link

2016-09-26 14:56 UTC, max3903 commented on mgmtsystem_severity/README.rst
> +* Loïc Faure-Lacroix <loic.lacroix@savoirfairelinux.com>
* Add yourself and me.

2016-09-26 14:58 UTC, max3903 requested changes

2016-10-23 18:49 UTC, dreispt requested changes

2016-10-23 18:49 UTC, dreispt commented on mgmtsystem_severity/__openerp__.py
> +    "complexity": "normal",
deprecated - remove

2016-10-23 18:49 UTC, dreispt commented on mgmtsystem_severity/model/mgmtsystem_severity.py
> +# -*- coding: utf-8 -*-
Missing copyright notice (please use short headers)

2016-10-23 18:49 UTC, dreispt commented on mgmtsystem_severity/model/mgmtsystem_severity.py
> +
Remove empty line

2016-10-23 18:49 UTC, dreispt commented on mgmtsystem_severity/model/mgmtsystem_severity.py
> +    category = fields.Selection((
Selection values usually is a List of tuples, rather than a Tuple of tuples.

2016-10-23 18:49 UTC, dreispt commented on mgmtsystem_severity/tests/__init__.py
> +]
AFAIK the `checks`variable is not needed (?)

2016-10-24 17:58 UTC, max3903 requested changes

2016-10-24 17:58 UTC, max3903 commented on mgmtsystem_severity/__openerp__.py
> -    "complexity": "normal",
@naousse Keep the website, license and category.

2017-04-25 22:51 UTC, merged