Mig mgmtsystem review to v. 10.0
OCA/management-system pull request #171
Opened 2017-03-14 11:22 UTC by eugen-don

Mig mgmtsystem review to v. 10.0

2017-05-05 08:22 UTC, dreispt commented on mgmtsystem_review/models/__init__.py
> +)
The previous format if OK (and more concise). No point in changing it.

2017-06-12 17:12 UTC, angelmoya commented on mgmtsystem_review/tests/test_create_review.py
>  from datetime import datetime
Question for odoo experts: 

could be better to replace ?: 
```
from datetime import datetime
...
datetime.now()

```
to : 

```
from odoo import fields
...
fields.datetime.now()
```

2017-06-13 07:42 UTC, eugen-don commented
Hi @max3903 @dreispt 
i had problems reverting or lets say rewriting the first commit message, luckily figured out how git reset command works.

I think this looks ok now?

2017-06-13 13:24 UTC, max3903 commented
@eugen-don Please look at the report attached:
[Review report (9).pdf](https://github.com/OCA/management-system/files/1071511/Review.report.9.pdf)

I can't see the title and the footer.

2017-06-13 13:24 UTC, max3903 requested changes
Report needs fixing.

2017-06-13 13:31 UTC, eugen-don commented
@max3903  how did you print this report i cant find the menuitem?

2017-06-13 13:32 UTC, max3903 commented
@eugen-don I created a review and went to the print menu.

2017-06-13 15:20 UTC, eugen-don commented
@max3903 

reports are OK, check it out one more time, paper format wasnt set accordingly.

2017-06-13 16:26 UTC, max3903 approved these changes

2017-06-14 07:38 UTC, eugen-don commented
ping @angelmoya

2017-06-14 07:49 UTC, angelmoya commented
Sorry @eugen-don this week I have a lot of work and no time to check this, maybe friday or next week.

Please @acm1pt-colorado check this

2017-06-14 08:15 UTC, ljimenezsidoo approved these changes
Hi @eugen-don tested on runbot, looks great

2017-06-14 08:20 UTC, angelmoya commented
On runbot I create "AngelMoyaReview" and get this error

```
Traceback (most recent call last):
  File "/home/odoo/odoo-10.0/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/.repo_requirements/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/home/odoo/odoo-10.0/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/home/odoo/odoo-10.0/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/home/odoo/odoo-10.0/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1037, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/odoo-10.0/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/home/odoo/odoo-10.0/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1057, in render
    return self.env[engine].render(self.id, qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: tuple index out of range
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_mgmtsystem_review_review_report_1735
  File "<template>", line 4, in body_call_content_1734
  File "<template>", line 74, in foreach_1722
  File "/.repo_requirements/odoo/odoo/models.py", line 5215, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: mgmtsystem_review.review_report
Path: /templates/t/t/div/div[4]/div[3]/t[1]/ul/li[1]/span
Node: <span t-field="response.user_input_line_ids[2].value_text"/>
```

2017-06-14 11:24 UTC, eugen-don commented
@angelmoya 
The reson for the error is that the your review contains survey answers from a user feedback form which isnt completed yet. See in your review there are survey answers from surveys that are partly completet. Try to first complete the survey and then add the survey to the review again.

2017-06-14 11:29 UTC, angelmoya commented
Nice @eugen-don , would be better to show this information in warning to prevent this error.

2017-06-14 14:33 UTC, eugen-don commented
@angelmoya 
indeed thanks for the good idea. 

@dreispt @max3903 
This behaviour is the same in all versions.

I see two ways of correcting this:
1. add a filter to the Survey Answers field in the view definition to only show complete answers
2. edit the template to check if the surveys answer is completed and only print the answer if it is completed.

Since the first option is easier to code and i assume that including incomplete or empty answers in the modules data and reports provides no benefits, id like to stick to the first option.

What do you guys think?

2017-06-14 14:35 UTC, max3903 commented
@eugen-don Yes, first option makes more sense.

2017-06-16 18:16 UTC, eugen-don commented
@dreispt 

could you merge?

2017-06-16 18:45 UTC, max3903 commented
@eugen-don Have you added the filter on the survey answer?

2017-06-16 19:18 UTC, eugen-don commented
@max3903  no since its not part of the migration, its an improvement and goes into a different PR

since the bug is present in versions 8.0 and 9.0 ill need to fix those first...

2017-06-16 19:31 UTC, merged