Mig document page work instructions to v. 10.0
OCA/management-system pull request #176
Opened 2017-03-14 11:29 UTC by eugen-don

Mig document page work instructions to v. 10.0

2017-03-21 22:01 UTC, dreispt commented
@eugen-don Can you please help reviewing OCA/knowledge#122 ?

2017-03-21 22:16 UTC, dreispt requested changes
I feel that something went wrong when porting the change history from 9.0 to 10.0.

2017-03-21 22:16 UTC, dreispt commented on document_page_procedure/__manifest__.py
> +    "version": "10.0.0",
10.0.1.0.0

2017-03-21 22:16 UTC, dreispt commented on document_page_procedure/__manifest__.py
> +    """,
Remove description key - we have the README for that.

2017-03-21 22:16 UTC, dreispt commented on document_page_procedure/__manifest__.py
> +        'document_page_work_instructions'
Hmm... module names are supposed to be singular, not plural.
Are you sure about this change?

2017-03-21 22:16 UTC, dreispt commented on document_page_quality_manual/README.rst
> +This module was written to provide a quality manual template. The template has the same structure as the ISO 9001 standard.
IMO the original form is better: we describe what the module does, not how it was done.

2017-03-21 22:16 UTC, dreispt commented on document_page_quality_manual/README.rst
> -   :target: https://runbot.odoo-community.org/runbot/118/9.0
Why are you removing the Runbot link?

2017-03-21 22:16 UTC, dreispt commented on document_page_quality_manual/README.rst
> +`here <https://github.com/OCA/management-system/issues/new?body=module:%20document_page_quality_manual%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Ex
8.0?

2017-03-26 14:06 UTC, eugen-don commented
Hi @dreispt 
I rebased the pull on latest V 9.0, but im still not familiar with the git magic you mentioned. Is there any template README file i could use?

2017-03-28 13:29 UTC, grindtildeath commented
@eugen-don 
Here are the OCA guidelines in case that's what you were looking for : 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
Other wise looks good to me. :+1:

2017-03-28 15:36 UTC, max3903 requested changes
@eugen-don In the README.rst, the link to Runbot and Github issues still points or uses version 9.0

2017-03-29 10:13 UTC, eugen-don commented
@grindtildeath 
Thanks for providing the resource.

2017-03-29 15:02 UTC, max3903 approved these changes

2017-03-29 16:20 UTC, sbidoul approved these changes

2017-03-29 16:41 UTC, max3903 commented
@dreispt Can you update your review please?

2017-03-30 07:42 UTC, dreispt approved these changes

2017-03-30 07:42 UTC, merged