[11.0][MIG] document page procedure
OCA/management-system pull request #214
Opened 2018-04-15 10:58 UTC by jalzaga

Module document_page_procedure Migration to version 11.0 #200

2018-09-28 18:06 UTC, ivantodorovich requested changes
Minor comment

I'm unsure about the resolution of git conflicts on the last commit. 
Is this the way to go when migrating modules?

2018-09-28 18:06 UTC, ivantodorovich commented on document_page_procedure/migrations/7.0.1.0/pre-migration.py
> +##############################################################################
remove old migration script

2018-10-06 10:50 UTC, jalzaga commented
@max3903 @pedrobaeza I cannot see what is the problem with the runbot. Could you please give me a clue?

2018-10-06 14:23 UTC, ivantodorovich commented
Seems to be unrelated to this PR. I've seen it failing like this in other PRs aswell

2018-10-06 14:23 UTC, ivantodorovich approved these changes

2018-10-06 22:37 UTC, max3903 requested changes
Minor fixes. 

It would be nice to split the README, but it can be done in a later PR. It's not blocking for this one.

Thanks!

2018-10-06 22:37 UTC, max3903 commented on document_page_procedure/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/118/10.0
/11.0

2018-10-06 22:37 UTC, max3903 commented on document_page_procedure/README.rst
> +`here <https://github.com/OCA/management-system/issues/new?body=module:%20document_page_procedure%0Aversion:%2010.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expect
11.0

2018-10-06 22:37 UTC, max3903 commented on document_page_procedure/README.rst
> +Changelog
This section can be removed.

2018-10-06 22:37 UTC, max3903 commented on document_page_procedure/__manifest__.py
> +    "website": "http://www.savoirfairelinux.com",
Can be replaced with https://github.com/OCA/management-system.

2018-10-16 11:56 UTC, jalzaga commented
Could someone unlock this PR? the error seems not to be related with the PR itself @ivantodorovich @max3903

2018-10-16 14:48 UTC, max3903 commented
@jalzaga Can you take care of my comments? Please bump the version to 11.0 in the readme.

2018-10-16 20:26 UTC, max3903 commented on document_page_procedure/README.rst
> +`here <https://github.com/OCA/management-system/issues/new?body=module:%20document_page_procedure%0Aversion:%2010.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expect
`version:%2011.0%0A%0A`

2018-10-16 21:14 UTC, jalzaga commented
Done @max3903

2018-10-16 21:19 UTC, max3903 approved these changes

2018-10-17 00:37 UTC, merged