[11.0][MIG] mgmtsystem nonconformity
OCA/management-system pull request #217
Opened 2018-04-15 19:55 UTC by jalzaga

Module mgmtsystem_nonconformity Migration to version 11.0 #200

2018-09-28 18:21 UTC, ivantodorovich commented
pls remove old migration scripts

2018-10-02 00:04 UTC, ivantodorovich commented
This PR only needs the removal of migration scripts and a rebase would be nice to make runbot and travis happy

2018-10-11 14:25 UTC, ivantodorovich commented
@jalzaga can you rebase, to make travis happy?

2018-10-17 01:44 UTC, ivantodorovich commented on mgmtsystem_nonconformity/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/128/10.0
update to 11.0

2018-10-17 01:44 UTC, ivantodorovich commented on mgmtsystem_nonconformity/README.rst
> +10.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
11.0

2018-10-17 01:44 UTC, ivantodorovich requested changes
update readme

2018-10-17 15:09 UTC, jalzaga commented
Done @ivantodorovich

2018-10-17 20:00 UTC, ivantodorovich commented
Please rebase, since this module depends on mgmtsystem_action.
That should make travis and runbot happy :)

2018-10-22 07:43 UTC, jalzaga commented
I have already done the rebase @ivantodorovich . Is there anything else missing?

2018-10-22 07:45 UTC, jalzaga commented
I have already done the rebase @ivantodorovich . Is there anything else missing?

2018-10-22 07:45 UTC, jalzaga commented
I have already done the rebase @ivantodorovich . Is there anything else missing?

2018-10-22 13:32 UTC, max3903 commented
@jalzaga Travis and Runbot are red. You still need to fix those errors. Thanks!

2018-10-23 16:11 UTC, ivantodorovich requested changes
I think those lines are the ones making travis and runbot red.
Those test cases make some database errors to appear in the logs. 
I would just remove them, what do you think @max3903 ?

2018-10-23 16:11 UTC, ivantodorovich commented on mgmtsystem_nonconformity/tests/test_cause.py
> +            self.env['mgmtsystem.nonconformity.cause'].create({})
This line

2018-10-23 16:11 UTC, ivantodorovich commented on mgmtsystem_nonconformity/tests/test_origin.py
> +            self.env['mgmtsystem.nonconformity.origin'].create({})
and this line

2018-10-23 23:18 UTC, max3903 commented
@ivantodorovich :+1:

2018-10-25 17:20 UTC, ivantodorovich commented
Thanks for that commit @jalzaga 

Travis is complaining because of the now unused IntegrityError. Please remove it from the imports aswell.
```
======== Testing test_flake8 ========
mgmtsystem_nonconformity/tests/test_cause.py:22:1: F401 'psycopg2.IntegrityError' imported but unused
mgmtsystem_nonconformity/tests/test_origin.py:21:1: F401 'psycopg2.IntegrityError' imported but unused
```

Runbot is still complaining, becase of this line:
```
2018-10-25 15:29:03,782 165 WARNING openerp_test odoo.models: ir.cron.create() includes unknown fields: function, model
```
It's a migration error in the `mgmtsystem_action` module. `ir.cron` wasn't migrated properly.
It is fixed on this commit: https://github.com/OCA/management-system/pull/236/commits/200f73f10f4fb2bed72161ce1569375a473be8cd (PR https://github.com/OCA/management-system/pull/236)

Since it's unrelated to this PR, I would just ignore it. But, please, do remove the imported IntegrityError

2018-10-26 15:30 UTC, jalzaga commented
Done @ivantodorovich

2018-10-26 18:07 UTC, ivantodorovich approved these changes

2018-10-26 18:09 UTC, ivantodorovich commented
Thanks!
LGTM 👍 

If you can review https://github.com/OCA/management-system/pull/236, among other things, it fixes the `ir.cron` in `mgmtsystem_action` that's causing runbot to complain.

2018-10-26 18:33 UTC, max3903 approved these changes

2018-10-26 18:33 UTC, merged