[ADD] mgmtsystem_consent: Ask for consent for data processing
OCA/management-system pull request #226
Opened 2018-06-28 13:01 UTC by Yajo

This addon makes it possible to define which partners are included
in any management system, and to define an automated explicit consent
acceptance system.

I'm not sure if this should go here or in OCA/data-protection, since it has much to do with both places... :thinking: 

Well, publishing here for now.

@Tecnativa

2018-06-28 16:39 UTC, pedrobaeza requested changes
Seeing the content, I think this should go on OCA/data-protection, although depending on mgmt_system

You should add some basic tests, avoiding mocks as possible, to be sure about the features.

2018-06-28 16:39 UTC, pedrobaeza commented on mgmtsystem_consent/models/res_partner.py
> +            one.mgmtsystem_consent_ids_count = len(one.mgmtsystem_consent_ids)
Remember to use `read_group` for not impacting too much on performance.

2018-06-28 16:39 UTC, pedrobaeza commented on mgmtsystem_consent/readme/DESCRIPTION.rst
> +This module aims for GDPR compliance, enabling the user to define a set of
Put a more generic description, although the GDPR example can be also here.

2018-06-28 16:55 UTC, dreispt commented
There are many managerial related aspects of "Data privacy and protection" that are better modeled as a "Management System". It is a grey area but I tend to agree with Pedro, and prefer to add that to the data-privacy repo.

More specifically on the features added, it claims to be a consent record, rather than an actual process/procedure management system, so that left me confused.

Also the description states that we are storing consent for people to be included in management systems. For the use cases I'm familiar with this does not make sense: these systems are integral part of my operation, maybe even mandatory by industry or government regulation, and people can't opt out.

Maybe a more specific examples could help understanding the use case this feature is targeting.

2018-06-29 07:33 UTC, Yajo commented
Before you lose more time reviewing, I'm then gonna narrow this PR here to just the modifications to the base mgmtsystem addon I need, and then open a new one in data-protection for the new mgmtsystem_consent one.

Somebody can set as WIP.

2018-06-29 08:17 UTC, Yajo commented
After some insightful conversation with @pedrobaeza, this is gonna fully land in OCA/data-protection.

2018-06-29 08:17 UTC, closed without merging