13.0 mig mgmtsystem survey
OCA/management-system pull request #270
Opened 2019-11-08 21:01 UTC by ernestotejeda

Depends on:
- [ ] https://github.com/OCA/management-system/pull/268

As this module depends on https://github.com/OCA/management-system/pull/268 I have included here the commits of that PR so it can be functionally tested.

Cc @Tecnativa TT20485

2019-11-09 13:22 UTC, ernestotejeda commented
As https://github.com/OCA/management-system/pull/268 is merged i rebased and cleaned up the commit history a bit

2019-11-13 11:12 UTC, Tardo approved these changes
:+1: LGTM

2019-11-13 11:36 UTC, pedrobaeza requested changes

2019-11-13 11:36 UTC, pedrobaeza commented on mgmtsystem_survey/models/survey_survey.py
> +    state = fields.Selection(selection_add=[("management_system", "Management System")])
You must create a pre-migration script for this that sets this value in if previous stage was `mgmtsystem_survey_type`

2019-11-13 21:37 UTC, ernestotejeda commented
changes done

2019-11-15 00:11 UTC, pedrobaeza commented on mgmtsystem_survey/migrations/13.0.1.0.0/pre-migration.py
> +        WHERE s.stage_id = ss.id
Don't use this flaw connection. Instead get the `res_id` of the XML-ID:
```suggestion
            LEFT JOIN ir_model_data imd ON imd.res_id = s.stage_id AND imd.module = 'mgmt_survey' AND imd.name = 'mgmtsystem_survey_type'
```

2019-11-15 17:08 UTC, ernestotejeda commented
Changes done

2019-11-17 14:15 UTC, pedrobaeza approved these changes

2019-11-17 14:15 UTC, pedrobaeza commented
/ocabot merge

2019-11-17 15:44 UTC, pedrobaeza commented
/ocabot merge

2019-11-17 18:02 UTC, merged