[13.0][MIG] mgmtsystem_nonconformity: Migration to 13.0
OCA/management-system pull request #275
Opened 2019-11-27 04:24 UTC by ernestotejeda

Cc @Tecnativa TT20483

2019-11-27 15:59 UTC, Tardo requested changes

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +                    x.stage_id.is_ending for x in nc._get_all_actions()
```suggestion
                    nc._get_all_actions().mapped('stage_id.is_ending')
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +            dt1 = fields.Datetime.from_string(dt1_text)
Be carefully... since 12.0 Odoo uses native python datetime (not strings)

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +            dt2 = fields.Datetime.from_string(dt2_text)
Same here...

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +            nc.days_since_updated = self._elapsed_days(nc.create_date, nc.write_date)
create_date and write_date are objects, not strings.

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +        is_writing = "is_writing" in self.env.context
```suggestion
        is_writing = self.env.context.get('is_writing', False)
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +                    vals["kanban_state"] = "normal"
```python
if any(self.filtered(lambda x: x.kanban_state != "normal)):
    vals["kanban_state"] = "normal"
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +                if nc.state != "done" and nc.closing_date:
```suggestion
                elif nc.state != "done" and nc.closing_date:
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
> +                if nc.state == "open" and was_not_open[nc.id]:
```suggestion
                elif nc.state == "open" and was_not_open[nc.id]:
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_cause.py
> +                name = obj.parent_id.name_get()[0][1] + " / " + name
```python
            if obj.parent_id:
                name = obj.parent_id.name_get()[0][1] + " / " + name
            else:
                name = obj.name
```
For more information see: https://docs.python.org/3/tutorial/classes.html#python-scopes-and-namespaces

Or if you prefer:
```python
            name = obj.parent_id.name_get()[0][1] + " / " + name if obj.parent_id else obj.name
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/models/mgmtsystem_nonconformity_origin.py
> +            name = obj.name
The same as in the other case

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/tests/__init__.py
> +##############################################################################
Use a short license comment

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/tests/test_nonconformity.py
> +        super(TestModelNonConformity, self).setUp()
```suggestion
        super().setUp()
```

2019-11-27 15:59 UTC, Tardo commented on mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
> +          <!--
If not used :fire:

2019-11-28 08:52 UTC, chienandalu approved these changes
Attend @Tardo comments. Otherwise LGTM

2019-11-28 15:24 UTC, ernestotejeda commented
Changes done

2019-11-30 12:50 UTC, pedrobaeza approved these changes

2019-11-30 12:50 UTC, pedrobaeza commented
As comments have been attended:

/ocabot merge

2019-11-30 13:08 UTC, merged