[13.0][MIG] mgmtsystem_claim
OCA/management-system pull request #314
Opened 2020-03-23 14:50 UTC by flachica

2020-03-23 15:05 UTC, flachica commented
This [fail](https://travis-ci.org/github/OCA/management-system/jobs/665907128#L775) is because need wait to this [PR](https://github.com/OCA/crm/pull/311) be merged

2020-06-22 17:27 UTC, FernandoRomera commented
@flachica, could you rebase this PR to continue it?.

2020-06-22 17:52 UTC, flachica commented
> @flachica, could you rebase this PR to continue it?.

Forced push

2020-06-23 05:17 UTC, FernandoRomera commented
Have you rebased over current 13.0 branch?

2020-06-23 16:16 UTC, flachica commented
> Have you rebased over current 13.0 branch?

Yes, but as you can see [here](https://travis-ci.org/github/OCA/management-system/jobs/700977318#L789), this module depends of OCA/crm/crm_claim. crm_claim is migrated yet but travis does not pulled it

2020-07-17 14:30 UTC, flachica commented
> Have you rebased over current 13.0 branch?

I included crm on oca_dependecies and test was passed

2020-07-18 05:38 UTC, FernandoRomera requested changes

2020-07-18 05:38 UTC, FernandoRomera commented on mgmtsystem_claim/views/mgmtsystem_claim.xml
> +                            domain="[('stage','in',(%(mgmtsystem_claim.stage_draft)d, %(mgmtsystem_claim.stage_open)d))]"
Replace domain="[('stage','in', by domain="[('stage_id','in',

2020-07-18 05:38 UTC, FernandoRomera commented on mgmtsystem_claim/views/mgmtsystem_claim.xml
> +                            domain="[('stage','=', %(mgmtsystem_claim.stage_pending)d)]"
Replace domain="[('stage','=', by domain="[('stage_id','=',

2020-07-19 05:26 UTC, FernandoRomera approved these changes
Functional review, ok.

2020-07-19 08:13 UTC, dreispt approved these changes

2020-07-19 08:13 UTC, dreispt commented
/ocabot merge nobump

2020-07-19 08:33 UTC, merged