[MIG] mgmtsystem_hazard: Migration to 17.0
OCA/management-system pull request #572
Opened 2024-02-20 19:16 UTC by ThinkopenDev

Straightforward migration from 16.0

2024-04-21 20:27 UTC, mymage commented
@ThinkopenDev please re-push so runboat will go green.

2024-04-22 14:52 UTC, mymage requested changes

2024-04-22 14:52 UTC, mymage commented on pandoc-3.1.12.1-1-amd64.deb
I think that this sliped inside the commit but must be deleted.

2024-04-23 18:24 UTC, ThinkopenDev commented on pandoc-3.1.12.1-1-amd64.deb
Sorry, this PR was closed on accident.
Meanwhile, we've pushed a new commit to remove the *.deb files.
I can't find option to re-open this PR, should we create a new one or is it OK for now?

2024-04-24 08:18 UTC, mymage commented on pandoc-3.1.12.1-1-amd64.deb
If I remember well you have the possibility to reopen a PR you have closed, but I may be wrong.
I see the new PR, I will put comment there.

2024-05-19 16:54 UTC, max3903 commented
/ocabot migration mgmtsystem_hazard

2024-05-21 17:08 UTC, mymage commented
Hi @ThinkopenDev, the repo was fixed (see #585).
Then I think you have to re-push this after a rebase. Thanks!

2024-09-14 17:33 UTC, dreispt requested changes
I'm sorry, this migration attempt got the history wrong, and rebase doesn't work.
It needs to be re-done using the recipe linked in the migration Issue.

2024-09-21 18:31 UTC, closed without merging