[18.0][MIG] document_page_quality_manual: Migration to 18.0
OCA/management-system pull request #608
Opened 2024-11-08 07:57 UTC by Kimkhoi3010

2024-11-12 04:58 UTC, xaviedoanhduy requested changes

2024-11-12 04:58 UTC, xaviedoanhduy commented on document_page_quality_manual/test-requirements.txt
> +odoo-addon-document_page @ git+https://github.com/OCA/management-system.git@refs/pull/504/head#subdirectory=document_page
```suggestion
odoo-addon-document_page @ git+https://github.com/OCA/knowledge.git@refs/pull/504/head#subdirectory=document_page
```

2024-11-19 00:23 UTC, max3903 commented
/ocabot migration document_page_quality_manual

2024-11-28 10:04 UTC, ajaniszewska-dev commented on document_page_quality_manual/readme/CONFIGURE.md
> +- go to Management Systems \> Documentation \> Work Instructions
i find it misleading/too general, as per usage.md we need to tick this option ![image](https://github.com/user-attachments/assets/4ee29770-b6f8-4492-ae12-6e6bf42aaa70)

2024-11-29 13:34 UTC, max3903 commented on document_page_quality_manual/readme/CONFIGURE.md
> +- select the Work Instructions category and edit the template
```suggestion
To edit the quality manual template:

- Go to Management Systems \> Configuration \> Categories
- Select the Quality Manual category
- Edit the content
```

2024-11-29 13:35 UTC, max3903 commented on document_page_quality_manual/__manifest__.py
> +    "depends": ["document_page"],
```suggestion
    "depends": ["mgmtsystem_manual"],
```

2024-11-29 13:37 UTC, max3903 commented on document_page_quality_manual/readme/CREDITS.md
> +
```suggestion
```

2024-11-29 13:38 UTC, max3903 commented on document_page_quality_manual/readme/USAGE.md
> +- Create a new page and select the Quality Manual category.
```suggestion
To enter your quality manual:

- Go to Management Systems \> Documentation \> Manuals
- Create a new page
- Enter a title
- Select the Quality Manual category
- Fill in the content
```

2024-11-29 13:39 UTC, max3903 commented on document_page_quality_manual/static/description/icon.png
@Kimkhoi3010 Please update the icon using this one:
https://github.com/OCA/management-system/blob/17.0/mgmtsystem/static/description/icon.png

2024-11-29 13:53 UTC, ajaniszewska-dev commented on document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
could we update this with some new screenshot?

2024-12-02 03:01 UTC, Kimkhoi3010 commented on document_page_quality_manual/static/description/icon.png
thank for your time !

2024-12-02 03:08 UTC, Kimkhoi3010 commented on document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
thank for your time !

2024-12-02 03:44 UTC, max3903 commented on document_page_quality_manual/__manifest__.py
> +    "images": ["images/wiki_pages_quality_manual.jpeg"],
```suggestion
    "images": ["static/description/quality_manual_form.png"],
```

2024-12-02 03:45 UTC, max3903 commented on document_page_quality_manual/images/wiki_pages_quality_manual.jpeg
@Kimkhoi3010 Please delete this file.

2024-12-02 03:46 UTC, max3903 requested changes
Still need some fixes and squashing migration commits

2024-12-02 04:27 UTC, Kimkhoi3010 reviewed
@max3903 Why you delete test-requirements.txt when we need it to pass test case?

2024-12-03 00:28 UTC, max3903 commented
@Kimkhoi3010 Because we are ready to merge.

2024-12-03 00:30 UTC, max3903 commented
/ocabot merge nobump

2024-12-03 00:34 UTC, merged